### ISSUE TITLE
dbo.get_count_nonzerobucket(@Bitmask) missing

### ISSUE THREAD

**Issue by mpaion** [shuvava/mssql-hll#1]

**Comment by Jkarioun** [comment]
@shuvava this function is missing from your implementation for testing. Can you add it to the repository?

From the name of it, it looks like it estimates determines whether the buckets are all 0. If you are working only with non-empty hashes, you can replace: 

[SET @num_zero = @m - dbo.get_count_nonzerobucket(@Bitmask)](https://github.com/shuvava/mssql-hll/blob/master/hll_get_estimatation.sql#L12)

with:

SET @num_zero = 1 

for a very temporary fix 😄

**Comment by shuvava** [comment]
I added implementation of that function

**Comment by mpaion** [comment]
Thanks

< committed to your business >

		
Matteo Piazza
CEO e CTO, Aion Srls
+39 333 7908486 | ***@***.*** | www.aionteam.it



Inviato da iPhone 
sorry for the typos
